- contract_function_params.go
- contract_function_result.go
- contract_function_selector.go
- Implement `ContractFunction*.[Int|Uint]8[Array]()`    
- Implement `ContractFunction*.[Get|Add]Bytes32[Array]()`
Signed-off-by: Daniel Akhterov <akhterovd@gmail.com>
> Implement 8 bit variants for int and uint and bytes32 in function result/params/selector

- account_create_transaction_test.go
- account_delete_transaction_test.go
- account_update_transaction_test.go
- contract_create_transaction_test.go
- contract_delete_transaction_test.go
- contract_execute_transaction_test.go
- contract_update_transaction_test.go
- file_append_transaction_test.go
- file_create_transaction_test.go
- file_delete_transaction.go
- file_delete_transaction_test.go
- file_update_transaction_test.go
- freeze_transaction_test.go
- query_builder.go
- system_delete_transaction_test.go
- system_undelete_transaction_test.go
- transaction_builder.go
- utilities_for_test.go
This adds basic validation to the transaction builder, making it where a `.Build()` call also returns an LocalValidationError if validation fails. The logic in the transaction builder is also improved to prevent nil pointer access errors at run-time.
> add basic validation to the transaction builder

- consensus_topic_info_query.go
- query_builder.go
- adds the method name to the switch in query builder
- handles potential nil values during execution
> Consensus Topic Info Query Fixes

- account_update_transaction_test.go
Before it was querying for the receipt of the original account create transaction instead of the account update transaction and then immediately requesting the account info -- if it did it fast enough it would get the original key instead of the updated key because consensus had not been reached on the network, resulting in the test failing occasionally.
> Fix TestAccountUpdateTransaction_Execute so it always waits for the update

- client.go
- crypto.go
- errors.go
- query_builder.go
- transaction.go
As a side effect, grpc status code is now exposed in `ErrHederaNetwork`
also simplifies the `___KeyFromString` functions
> Retry on Unavailable and ResourceExhausted

- query_builder.go
- transaction.go
set the precheck code to TRANSACTION_EXPIRED when time out happens at client side & the precheck code is OK
issue #74
> fix issue 74

- transaction_id.go
I got the following error when using gomobile bind:
transaction_id.go:21:42: constant 5000000000 overflows int
I changed the types to int64 and that seems to resolve the issue.
> Update transaction_id.go to resolve overflow error

- .github/workflows/main.yml
Requires CODECOV_TOKEN setup as a github action secret before this will work.
> Setup code coverage

- contract_create_flow.go
> fix: deprecated ContractCreateFlow.[Set|Get]ProxyAccountID

- account_balance.go
- token_balance_map.go
- token_decimal_map.go
The NewAccountBallanceQuery was depricated by mistake, this PR reverts this. 
This PR modifies:
account_balance.go
token_balance_map.go
token_decimal_map.go
Fixes # [589](https://github.com/hashgraph/hedera-sdk-go/issues/589)
> Revert NewAccountBalanceQuery deprecation

- .github/workflows/build.yml
- .github/workflows/main.yml
- .github/workflows/previewnet.yml
- .github/workflows/testnet.yml
Currently all builds are failing mainly because of the Go version not being supported anymore.
This PR modifies the workflow files to fix the builds.
> Bump github actions and Go version

- CHANGELOG.md
- client.go
- utilities_for_test.go
There was a 10 seconds blocking when creating a new Client. This PR removes the blocking.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/579
Added the use of context.Context in Client.go. For custom networks /i.e. not mainnnet, testnet, previewnet/ the network update is off by default, because there are no mirror nodes to update.
> Fixed the 10 seconds blocking on creating a Client

- .golangci.yml
- account_balance.go
- client.go
- contract_function_parameters.go
- ed25519_private_key.go
- examples/create_simple_contract/main.go
- examples/create_stateful_contract/main.go
- examples/zero_token_operations/main.go
- file_append_transaction.go
- managed_network.go
- token_associate_transaction.go
- token_dissociate_transaction.go
This PR contains only fixes for lint errors. 
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/609
1. Modifies `.golangci.yml` to remove warnings for deprecated checks. Those checks are being done by `unused` check. 
2. There was a redundant `if` statement in `managed_network.go`, the logic of this file will be reviewed and eventually refactored.  
3. Added some `//no lint` for the deprecated `pb.TokenBalances`. This functionality will be removed, once we have it released to mainnet. so it isn't exactly deprecated yet.
4. The rest of the files are just following lint recommendations.
> Fix lint errors

- CHANGELOG.md
- address_book_query.go
- client.go
This PR modifies removes the panic when there is an error getting the address book from mirror node.
It should now just return an error.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/625
> Fix panic in address book query

- address_book_query.go
- client.go
- client_unit_test.go
- managed_network.go
- mock_test.go
Schedule Network update was a recursive call. This PR changes this method in client.go to use a loop instead of recursive call.
In addition also fixes ClientFor/Previewnet/Testnet/Mainnet methods setting the wrong LedgerID.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/619 https://github.com/hashgraph/hedera-sdk-go/issues/624
> Fix schedule network recursive call

- token_nft_info.go
Just a field name change. It was wrongfully renamed. This the correct one as it is in the proto.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/631
> Change AllowanceSpenderAccountID to SpenderID

- account_id.go
This PR updates the AccountID object to allow users to directly call the IsZero() and Equals() methods on an AccountID object to enable direct comparison of two AccountID objects and to check whether or not an AccountID is the Zero Account ID.
> Expose AccountID Equality Methods

- transaction.go
Expose a method to get the SignedTransaction body bytes before it is signed.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/643
> Add method for getting SignedTransaction body bytes

- client_unit_test.go
- transaction.go
This PR fixes the issue where `GetTransactionHash` would return nil, and creating a transaction with multiple NodeAccountId's would panic.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/654, https://github.com/hashgraph/hedera-sdk-go/issues/640
> Fix panic in multiple node account id locking

- client.go
- client_all_test.go
- client_unit_test.go
- managed_node_address_unit_test.go
- tls_e2e_test.go
Just updating mirror node endpoints.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/665 https://github.com/hashgraph/hedera-sdk-go/issues/663
> Update mirror node endpoints

- client.go
- client_all_test.go
- client_unit_test.go
- managed_node_address_unit_test.go
- tls_e2e_test.go
This reverts commit d2e046de6d10ad1b499ab041bd48bf54b39a4bae.
Reverting the commit. Port 5600 is not serving.
> Revert "Update mirror node endpoints (#677)"

- address_book_query_e2e_test.go
- contract_update_transaction.go
The MaxAutomaticTokenAssociations field in ContractUpdate should be set to 0 by default.
This PR just changes the ContractUpdate to not send MaxAutomaticTokenAssociations if it is 0.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/662
> Don't send MaxAutomaticTokenAssociations on ContractUpdate if not set

- examples/alias_id_example/main.go
Just changing `lazy account creation` to `auto account creation` in one example.
Fixes: https://github.com/hashgraph/hedera-sdk-go/issues/684
> Rename lazy to auto account creation in examples

- examples/account_create_token_transfer/main.go
Just changing the HIP583 example to run by default against `Testnet` instead of `Previewnet`
> fix: Change hip583 example to testnet

- account_allowance_approve_transaction.go
- address_book_query_e2e_test.go
- token_nft_allowance_e2e_test.go
Adds the possibility for a `spender` to allow another `spender` (delegate spender) to send NFT's.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/668, https://github.com/hashgraph/hedera-sdk-go/issues/667
> feat: Add delegating spender functionality for NFT

- crypto.go
- crypto_unit_test.go
- ecdsa_public_key.go
- examples/account_create_token_transfer/main.go
There is a typo in ECDSA. This PR fixes all occurrances.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/700
> Fix: Typo in ECDSA

- account_create_transaction_e2e_test.go
- transaction.go
- transaction_unit_test.go
TransactionFromByte hardcodes duration to 120s instead of reading it. This PR fixes this.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/664
> Fix: TransactionFromBytes remove hardcoded duration

- executable.go
- transaction_receipt_query.go
- transaction_receipt_query_unit_test.go
- transaction_record_query_unit_test.go
- transaction_response.go
When there is an error retrieving receipt, like `RECEIPT_NO_FOUND` the error is silenced and the status is `Success`.
This PR fixes this.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/672
The SDK retries to get the receipt even when the node returns `RECEIPT_NO_FOUND`, because we might try to get the receipt before it is ready.
When the receipt has expired, the node will return `RECEIPT_NO_FOUND`, in this case we will retry until we reach `MaxAttempts`.
**Checklist**
> Fix: Receipt silencing error

- account_info_query.go
- account_info_query_unit_test.go
- contract_info_query.go
- contract_info_query_unit_test.go
- file_info_query.go
- file_info_query_unit_test.go
- mock_test.go
- network_version_info_query.go
- nework_version_info_query_unit_test.go
- schedule_info_query.go
- schedule_info_query_unit_test.go
- token_info_query.go
- token_info_query_unit_test.go
- token_nft_info_query.go
- token_nft_info_query_unit_test.go
- topic_info_query.go
- topic_info_query_unit_test.go
- transaction_record_query.go
- transaction_record_query_unit_test.go
Each Query has a certain cost. When asked `GetCost()` the consensus node returns the cost of the query.
If the answer was below 25th, the SDK was returning 25th, so in effect making the minimum query cost 25th.
This PR removes this, the `GetCost()` now returns the correct amount even if it is below 25th.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/692
It's mostly tests in this PR.
**Checklist**
- [ x ] Documented (Code comments, README, etc.)
- [ x ] Tested (unit, integration, etc.)
> Fix: Remove minimum requirement for 25th on queries

- transaction_id.go
- transaction_id_unit_test.go
When the transaction ID starts with 0, when the `String()` is called it trims the leading zeroes. This PR fixes this, so it is consistent with Mirror Node.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/733
> Fix transaction ID with leading zeroes

- .golangci.yml
- account_id.go
- account_id_unit_test.go
- client.go
- client_e2e_test.go
- contract_id.go
- contract_id_unit_test.go
- delegatable_contract_id.go
- delegate_contract_id_unit_test.go
- errors.go
- file_id.go
- network.go
- schedule_create_transaction_unit_test.go
- schedule_id.go
- token_allowance_unit_test.go
- token_balance_map_unit_test.go
- token_decimal_map_unit_test.go
- token_id.go
- topic_id.go
- topic_info_query_unit_test.go
LedgerID is just a way of representing networks: mainnet, testnet, previewnet, other.
LegerID identifier was already built, but wasn't finished properly. This PR finishes the implementation.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/603
**Checklist**
- [ x ] Documented (Code comments, README, etc.)
- [ x ] Tested (unit, integration, etc.)
> Feat: Add LedgerID identifier functionality

- client-config-with-operator.json
- client.go
- client_all_test.go
- client_unit_test.go
This PR adds the option to be able to create a client from config file without mirror network.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/748
**Checklist**
- [ x ] Tested (unit, integration, etc.)
> feat: Add option to create file from config without mirror network

- .github/workflows/build.yml
- address_book_query_e2e_test.go
- managed_network.go
- mirror_node.go
- mock_test.go
- network.go
- network_unit_test.go
This PR fixes some concurrency issues with the Network instances, related to accessing `healthyNodes`. It's protecting only the part of the instance which is used when executing transactions.
Fixes #762
Fixes #761 
**Checklist**
> Fixed network increase backoff concurrency issue

- contract_create_flow.go
- contract_create_flow_e2e_test.go
- contract_create_transaction_e2e_test.go
ContractCreateFlow was failing/passing depending on whether the user passed hex/ascii and also size.
It now works with ascii and does not depend on the size of the contract.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/758
**Checklist**
> Fix: ContractCreateFlow

- .github/workflows/build.yml
- one_signature_e2e_test.go
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/763
The `-race` for `testnets` will be added in another PR.
**Checklist**
> Feat: Add race flag to e2e tests

- account_id.go
- account_id_e2e_test.go
- account_id_unit_test.go
- contract_id.go
- contract_id_e2e_test.go
- contract_id_unit_test.go
- utilities_for_test.go
This PR adds `PopulateAccountNum()` to AccountID and ContractID. 
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/782
**Checklist**
> Feat: Add UpdateAccountNum

- .github/workflows/build.yml
- topic_message_query.go
- topic_message_query_e2e_test.go
This PR fixes data race in TopicMessageQuery.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/786
**Checklist**
> Fix: Data race in topic message query

- transaction_receipt_query_unit_test.go
We already retry when the receipt status is UNKNOWN, this PR just adds a test verifying that's the case.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/788
**Checklist**
> Test: Add receipt status unknown test

- client_e2e_test.go
- network.go
When a transaction has Node Account Id with is not present in the current network the client panics. This PR fixes this. It should now fail gracefully.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/802
**Checklist**
> Fix: Panic when node account id is not in network list

- transaction_id_unit_test.go
This PR adds a test verifying that the generated transaction id's are unique by generating 100k ids within 0.1 seconds.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/800
**Checklist**
> Test: Unique concurent transaction ids

- file_append_transaction.go
- file_append_transaction_unit_test.go
- token_create_transaction.go
- token_create_transaction_unit_test.go
- topic_create_transaction.go
- topic_create_transaction_unit_test.go
- topic_message_submit_transaction.go
- topic_message_submit_transaction_unit_test.go
- fix serialization issues
- fix auto renew on token create tx
- fix return type on system delete tx
Fixes #809 
**Checklist**
> Various fixes

- Taskfile.yml
This PR adds a task to execute all examples.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/801
> Feat: Add run examples task

- account_id_e2e_test.go
- client_e2e_test.go
- go.mod
- go.sum
- transaction_receipt.go
- transaction_receipt_query_unit_test.go
- transaction_record.go
- transaction_record_query_unit_test.go
- transaction_response.go
- transfer.go
We need ToJSON method for receipt, record and response that matches the output of JS SDK.
This PR adds `MarshalJSON` to these structs that does this.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/797
**Checklist**
> Feat: Add ToJSON on recepit, record, response

- executable.go
Added check in the root `_execute` function about `nodeAccountIDs` and functionality to fetch node ID from client, if the structure is empty. 
#852
Fixes #
**Checklist**
> Fixed bug (Added check inside root  for nodeAccountId)

- ethereum_transaction_e2e_test.go
The latest Local Node does not produce consistent results for Ethereum transactions and causes `TestIntegrationEthereumTransaction` to have flaky behaviour.
The PR skips this test for the time being and it will be investigated in the future.
Fixes #
**Checklist**
> chore: Skip flaky `EthereumTransaction` e2e test

- .github/workflows/build.yml
This PR is introducing essential environment variables, `OPERATOR_KEY` and `OPERATOR_ID`, necessary for seamless integration of pull requests from forked repositories into the CI pipeline.
Fixes #
**Checklist**
> chore: add Operator Key and ID to CI workflow

- utilities_for_test.go
Methods like `NewIntegrationTestEnv` and `CloseIntegrationTestEnv` might panic ungracefully in certain circumstances.
This PR adds better error handling by adding asserts when error occures.
Fixes #943
**Checklist**
> fix: Add better error handling in test utils

- account_create_transaction_e2e_test.go
- serialize_deserialize_test.go
- token_nft_allowance_e2e_test.go
- token_update_nfts_transaction_e2e_test.go
- transaction.go
- transaction_e2e_test.go
Signing requires the transaction to be frozen. We need to make sure the request is frozen before signing. Add check for this and propagate `errTransactionIsNotFrozen` if the check fails.
Fixes #946
**Checklist**
> fix: Raise an error if the transaction is not frozen while signing

- file_info_query_e2e_test.go
- token_info_query_e2e_test.go
Revert the skipping of tests during the modularization triage
Fixes #
**Checklist**
> chore: revert the skipping of tests during the modularization triage

- mnemonic.go
- mnemonic_test.go
- Add custom derivation path capability
- Compatibility/ parity with EVM dev tools + wallets. Specifically:
- When working Metamask, you need to use the hardcoded derivation path in it, and in SDK there's also a (different) hardcoded derivation path.
- In EVM dev tools - web3.js/ethers.js/viem etc - they allow you to specify a custom derivation path, and do not force you to use the Ethereum one.
- The lack of support for custom derivation paths is a friction point for EVM developers onboarding into Hedera development
- This may have the effect of effectively discouraging use of the SDK, in favour of using 3rd party libraries that do support custom derivation paths
- we should aim to reduce the reliance on 3rd party dependencies in general, within code that is written …
> feat: custom derivation paths in Mnemonic ECDSA private key derivation

- README.md
- scripts/git-hooks/pre-commit
- scripts/install-hooks.sh
This  PR adds a pre-commit git hook that runs golangci-lint before each commit. 
This hook can be installed by running the `scripts/install-hooks.sh` script.
Fixes #1006 
**Checklist**
> chore: Add pre-commit git hook for golangci-lint

- account_balance_query_e2e_test.go
- account_id_e2e_test.go
- contract_create_flow.go
- file_append_transaction.go
- transaction_record_query_e2e_test.go
- transaction_response.go
When manual `ReceiptQuery` is executed, the status returned is not validated, meaning it will not return error object.
Error object is returned only when the receipt query is executed by `GetReceipt` on the transaction result.
Currently if a transaction fails with throttle status and we call `GetReceipt`, it will retry, but if we create the receipt separately it would not retry or return an error.
This causes some integration tests to have flaky behaviour. Additionally manual execution of `ReceiptQuery` will return no error when an error code is actually returned.
This PR:
1. Adds the ability to query child receipts from the transaction result.
2.  Replaces receipt query execution with `GetReceipt` in e2e tests.
3.  Replaces receipt query execution with `GetReceipt` in …
> fix: replace manual receipt query execution with `GetReceipt`

- node_create_transaction_e2e_test.go
- node_create_transaction_e2e_tests.go
This PR serves as a POC for using NodeCreateTransaction.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/1085
Can be merged even if POC as it adds an Integration test. CI will fail against `local-node` so the test will be disabled(It needs `Solo` configured in our CI).
**Checklist**
> feat: Add integration test for NodeCreateTransaction

- contract_function_parameters.go
- contract_function_parameters_e2e_test.go
- contract_function_result.go
- math.go
- math/math.go
- math_unit_test.go
Replace `/math` package
Fixes #1111
**Checklist**
> chore: Replace `/math` package

- transaction_response.go
> fix: Retry in case of throttle when calling `getRecord`

- contract_function_parameters_e2e_test.go
> chore: make uint tests run in parallel

- client.go
- client_e2e_test.go
Adding a new api that if a JSON config is provided there is no need for the address book update thread.
Fixes #1130
**Checklist**
> feat: create client without schedule network update

- key_list.go
- key_list_unit_test.go
Fixes https://github.com/hiero-ledger/hiero-sdk-go/issues/1159
> feat: sdd getters for internal list of keys + threshold value

- sdk/freeze_transaction.go
- sdk/freeze_transaction_unit_test.go
- sdk/prng_transaction_e2e_test.go
- sdk/prng_transaction_unit_test.go
This PR add unit/integration tests for `PrngTransaction` and `FreezeTransaction` and fixes a bug in `FreezeTransaction` where `protobufFromBytes` does not map the correct start time.
fixes: https://github.com/hiero-ledger/hiero-sdk-go/issues/1084
> test: Create additional unit/integration tests

- sdk/live_hash_delete_transaction_unit_test.go
- sdk/node_create_transaction_unit_test.go
- sdk/node_delete_transaction_unit_test.go
- sdk/node_update_transaction_unit_test.go
- sdk/prng_transaction_unit_test.go
- sdk/schedule_create_transaction.go
- sdk/schedule_create_transaction_unit_test.go
- sdk/schedule_sign_transaction_unit_test.go
- sdk/system_delete_transaction.go
- sdk/system_delete_transaction_unit_test.go
- sdk/system_undelete_transaction_unit_test.go
- sdk/token_airdrop_transaction_unit_test.go
- sdk/token_associate_transaction_unit_test.go
- sdk/token_burn_transaction_unit_test.go
- sdk/token_cancel_airdrop_transaction_unit_test.go
- sdk/token_claim_airdrop_transaction_unit_test.go
- sdk/token_create_transaction.go
- sdk/token_create_transaction_unit_test.go
Fixes
1. sdk/schedule_create_transaction.go
2. sdk/system_delete_transaction.go
3. sdk/token_create_transaction.go
Related issue: https://github.com/hiero-ledger/hiero-sdk-go/issues/1088
> Create additional from/to bytes tests - part 3

- sdk/nft_id.go
- sdk/token_nft_info_query_unit_test.go
- sdk/token_transfer_transaction_unit_test.go
> chore: Standardize NftId string format

- sdk/transaction.go
- sdk/utilities_for_test.go
This PR fixes a bug where `transactionFee` gets zeroed when a transaction is serialized (.toBytes) and not frozen beforehand.
This causes the transaction to fail with `INVALID_TX_FEE`. This could be reproduced with removing the default max fee from the test env client - the executable sets `transactionFee` from the client, if it's missing in the transaction body.
> fix: Add `transactionFee` in serialize/deserialize when tx is not frozen

- README.md
> chore: Remove protobuf version note in README

- sdk/crypto.go
- sdk/crypto_unit_test.go
- sdk/ecdsa_private_key.go
- sdk/ecdsa_public_key.go
- sdk/ethereum_transaction_e2e_test.go
- sdk/query.go
- sdk/transaction.go
This PR introduces two key enhancements to the Hedera Go SDK's handling of ECDSA private keys:
1. **Addition of `GetRecoveryId` Method**: A new method, `GetRecoverID`, has been added to the `PrivateKey` struct for ECDSA keys. This method retrieves the recovery ID (also known as the 'v' value) associated with ECDSA signatures, facilitating signature verification processes.
2. **Modification of the `Sign` Method Output**: The `Sign` method for ECDSA private keys has been updated to return only the `r` and `s` components of the signature, reducing the output from 65 bytes to 64 bytes. This change aligns the SDK's behavior with standard ECDSA signature formats, which typically include only the `r` and `s` values.
These updates enhance the SDK's compatibility with standard …
> feat: Аdd `GetRecoveryId` and align ECDSA signing with other SDKs

- sdk/address_book_query.go
- sdk/client.go
- sdk/client_e2e_test.go
- sdk/file_id.go
- sdk/file_id_unit_test.go
- sdk/mirror_network.go
- sdk/topic_message_query.go
This PR aims to provide new APIs to allow a user to set which realm and shard from which to retrieve a static file, as well as fixing the `AddressBookQuery` used by `Client.forMirrorNetwork()`.
- `uint64 realm`: The realm from which to get the address book file ID.
- `uint64 shard`: The shard from which to get the address book file ID.
- `uint64 realm`: The realm from which to get the fee schedule file ID.
- `uint64 shard`: The shard from which to get the fee schedule file ID.
- `uint64 realm`: The realm from which to get the exchange rates file ID.
- `uint64 shard`: The shard from which to get the exchange rates file ID.
**Description**: `forMirrorNetwork` uses a list of mirror node URLs to query and get the address book for a network and uses that address book to …
> feat: Non-Zero Realm and Shard File IDs for Static Files

- sdk/transaction_response.go
Fixes an issue where the receipt children were not included when the transaction throttled, when `setIncludeChildren` is set to true.
This issue can be seen in the CI once in a while.
Fixes #
**Checklist**
> fix: `receipt.setIncludeChildren` when throttle

- sdk/file_append_transaction.go
- sdk/file_append_transaction_unit_test.go
This PR makes `FileAppendTransaction` validate it's receipts for all chunks. This improves UX and removes false-positives.
Fixes #
**Checklist**
> fix: Validate receipt for multiple file appends

- sdk/transaction.go
- sdk/transaction_e2e_test.go
- Fixes `TransactionSign` and `TransactionExecute` to work with chunked transactions by calling the overridden implementations.
Fixes #1472
**Checklist**
> fix: Static utility transaction methods for chunked transactions

- sdk/transaction.go
- tck/cmd/server.go
- tck/methods/file.go
- tck/methods/token.go
fix some inconsistent function name in comment
Fixes #
**Checklist**
> chore: fix some inconsistent function name in comment
