hiero-ledger/hiero-sdk-go

examples/create_account/main.go, examples/create_file/main.go, examples/get_account_balance/main.go
This fixes the error mentioned in #5
=> Load Operator ID from an environment variable for examples

account_info_query.go, account_update_transaction_test.go, client.go, contract_create_transaction_test.go, contract_update_transaction_test.go, crypto.go, crypto_test.go, file_create_transaction.go, file_info_query.go, file_update_transaction.go, file_update_transaction_test.go, keystore.go, keystore_test.go, mnemonic_test.go, transaction.go
=> KeyStores, KeyLists, and other Crypto Parity issues

examples/create_account/main.go, examples/create_file/main.go, query_builder.go, status.go, transaction_record_query.go
- fixes the panic on status check
- updates the record status behavior
=> Status and Record updates

examples/create_account/main.go, examples/create_account_with_manual_signing/main.go, examples/create_account_with_threshold_keys/main.go, examples/delete_account/main.go, key_list.go, query_builder.go, threshold_key.go, transaction.go
Working on adding more examples, should help with #5
=> More Examples

examples/consensus_pub_sub/main.go, transaction_receipt.go
- add tryGet functions for possible nil values
- make ConsensusTopicSequenceNUmber and ConsensusTopicRunningHash private
- add missing getters
- add documentation for public functions and values
=> Improved Transaction Receipt

client.go, transaction.go
Note that I didn't add documentation because it already exists in #33
=> Rename Signer to TransactionSigner and make publicly accessable

client.go, go.mod, go.sum
=> Fix  documentatiion for client

file_append_transaction_test.go, file_contents_query_test.go, file_create_transaction_test.go, file_delete_transaction_test.go, file_info_query_test.go, file_update_transaction_test.go, transaction.go
=> Add E2E tests for File Transactions and Queries

contract_create_transaction_test.go, contract_delete_transaction_test.go, contract_execute_transaction_test.go, contract_info_query_test.go
=> Contract E2E Tests

consensus_message_submit_transaction_test.go, consensus_topic_create_transaction_test.go, consensus_topic_delete_transaction_test.go, consensus_topic_info_query_test.go, consensus_topic_update_transaction_test.go
=> Consensus E2E Tests

account_balance_query_test.go, account_info_query_test.go, account_records_query_test.go, account_stakers_query_test.go, consensus_message_submit_transaction_test.go, consensus_topic_info_query_test.go, contract_bytecode_query_test.go, contract_call_query_test.go, contract_info_query_test.go, contract_records_query_test.go, file_contents_query_test.go, file_info_query_test.go, get_by_solidity_id_query_test.go, transaction_receipt_query_test.go, transaction_record_query_test.go
Signed-off-by: Daniel Akhterov <akhterovd@gmail.com>
=> Fix *_query_test.go tests

errors.go
show complete error description with both the rpc code and description
issue #76 
Signed-off-by: Xin Li <xin.li@swirlds.com>
=> fix issue 76

query_builder.go, transaction.go
ErrHederaNetwork.StatusCode may be nil, so check it before accessing the value
issue #77
=> fix possible nil value access

CHANGELOG.md, examples/schedule_multisig_transaction/main.go, hbar.go, schedule_create_transaction_test.go, schedule_info.go
=> fix: Rename `ScheduleInfo.Signers` -> `ScheduleIfno.Signatories`

account_balance_query_test.go, schedule_info.go, topic_info_query_test.go
=> fix: deprecated ScheduleInfo.Signatories, added ScheduleInfo.Signers

examples/client_from_file/client_config_simple.json, examples/client_from_file/client_config_with_operator_testnet.json, examples/client_from_file/main.go
=> feat: Added client from file example

account_id.go, account_info.go, contract_id.go, contract_info.go, contract_log_info.go, crypto.go, errors.go, exchange_rate.go, file_id.go, file_info.go, key_list.go, live_hash.go, network_version_info.go, schedule_id.go, schedule_info.go, semantic_version.go, time.go, token_id.go, token_info.go, token_info_query_test.go, token_relationship.go, token_transfer.go, topic_id.go, topic_info.go, transaction_id.go, transaction_receipt.go, transaction_record.go, transfer.go
=> fix: fixed various null dereference in various fromBytes

examples/create_stateful_contract/main.go, time.go
=> fix: fixed durationFromProtobuf, create stateful contract example

token_create_transaction.go, token_update_transaction.go
=> fix: setTokenExiprationTime bug fix

errors.go, subscription_handle.go, topic_message_query.go, transaction_receipt_query.go, transaction_receipt_query_test.go, transaction_record_query.go
=> refactor: `TopicMessageQuery`

topic_message_query.go, topic_message_query_test.go
Resolves comments made on #166
=> fix the `TopicMessageQuery` refactor

transfer_transaction.go, transfer_transaction_test.go
=> fix: `TransactionTransfer.AddHbarTransfer()` 

mirror_node.go
=> feat: add basic TLS support for mirror node connections

account_balance.go, account_balance_query_test.go, token_balance_map.go, token_decimal_map.go
Resolves: #196 
Resolves: #195 
Resolves: #192
=> Implement  `AccountBalance[Tokens|TokenDecimals]` and deprecate `AccountBalance.Token`

executable.go, topic_message_query.go
Resolves: #197 
Warning: This is untested as there are no nodes that are down at the moment.
=> Update default retry handlers to retry on `INTERNAL` conditionally on `RST_STREAM` regex

fee_components.go, fee_data.go, fee_schedule.go, fee_schedules.go, fee_schedules_test.go, request_type.go, transaction_fee_schedule.go
=> feat: added parsing file 0.0.111 support

utilities_for_test.go
=> fix: CloseIntegrationTestEnv configuration file bug

.github/workflows/previewnet.yml, .github/workflows/testnet.yml
=> feat: add linting check to CI

examples/consensus_pub_sub/main.go, examples/consensus_pub_sub_chunked/main.go, examples/consensus_pub_sub_with_submit_key/main.go, examples/create_account/main.go, examples/create_account_with_manual_signing/main.go, examples/create_account_with_threshold_keys/main.go, examples/create_file/main.go, examples/create_simple_contract/main.go, examples/create_stateful_contract/main.go, examples/delete_account/main.go, examples/delete_file/main.go, examples/file_append_chunked/main.go, examples/get_account_balance/main.go, examples/get_account_info/main.go, examples/get_address_book/main.go, examples/get_file_contents/main.go, examples/get_query_cost/main.go, examples/ping_network/main.go, examples/schedule_multisig_transaction/main.go, examples/topic_with_admin_key/main.go, examples/transfer_hbar/main.go, examples/transfer_tokens/main.go, examples/update_account_public_key/main.go
=> refactor: clean up client creation in examples

custom_fee.go, custom_fixed_fee.go
=> feat: implemented helper methods for CustomFixedFee

crypto.go, crypto_test.go
=> fix: fixed invalid pem key nil dereference error

.github/dependabot.yml, .github/workflows/main.yml, .github/workflows/testnet.yml
- Add Dependabot
- Rename references to master
- Fix CI not running against main
**Checklist**
=> Add Dependabot

custom_fee.go, custom_fixed_fee.go, custom_fractional_fee.go, custom_royalty_fee.go, token_create_transaction_test.go
=> feature: added New* Set* Get* to custom fees

account_balance_query_test.go, account_create_transaction_test.go, custom_fixed_fee.go, status.go, token_burn_transaction_test.go, token_create_transaction_test.go, token_fee_schedule_update_transaction_test.go, token_mint_transaction_test.go, token_transfer_transaction_test.go, token_update_transaction_test.go, token_wipe_transaction_test.go, transfer_transaction.go
=> feat: adding more integration tests

fee_schedules_test.go, node.go
=> fix: certificate check

transaction.go
=> feat: implemented bare transaction helper methods

token_create_transaction.go, token_info.go
=> fix: added missing fee schedule key for token info

CHANGELOG.md, account_id.go, account_records_query_test.go, client.go, client_test.go, contract_function_selector.go, contract_id.go, executable.go, file_id.go, hbar_unit.go, legacy.go, managed_network.go, managed_node.go, managed_node_address.go, mirror_network.go, mirror_node.go, network.go, network_name.go, nft_id.go, node.go, request_type.go, schedule_id.go, status.go, token_id.go, token_supply_type.go, token_type.go, topic_id.go, utilities_for_test.go
=> feat: add TLS configuration support

status.go
=> feat: added CONSENSUS_GAS_EXHAUSTED status

CHANGELOG.md, client_unit_test.go, token_transfer_transaction_unit_test.go, transfer_transaction.go
Signed-off-by: Daniel Akhterov <daniel@launchbadge.com>
Fixes #320 
**Checklist**
=> fix: `TransferTransaction.GetTokenTransfers()`

examples/schedule_identical_transaction/main.go, mock_test.go, transaction_receipt_query.go, transaction_response.go
=> fix: `TransactionReceiptQuery` should not error if a receipt is present

account_id.go, go.mod, go.sum, token_id.go, token_nft_transfer.go, transfer_transaction.go, transfer_transaction_unit_test.go
=> feat: order protobuf transfers

account_create_transaction_e2e_test.go, account_id.go, account_id_unit_test.go, account_info.go, client_unit_test.go, contract_id.go, crypto.go, examples/alias_id_example/main.go, file_id.go, go.mod, go.sum, id.go, mock_test.go, nft_id.go, schedule_id.go, status.go, token_id.go, topic_id.go, transaction_e2e_test.go, transaction_id.go, transaction_id_unit_test.go, transaction_receipt_query.go, transaction_record.go, transaction_record_query.go, transfer_transaction_e2e_test.go, utilities_for_test.go
=> feat: implementing HIP-206 changes

token_update_transaction.go
=> fix: added missing pause key to token update transaction

crypto.go, token_transfer.go, transfer_transaction.go
=> feat: implementing auto account creation

token_id.go, topic_id.go
Added to and from solidity methods for token ID and topic ID
Fixes # https://github.com/hashgraph/hedera-sdk-go/issues/362
**Checklist**
=> Add to and from solidity

account_id.go, account_info.go, client.go, contract_id.go, contract_info.go, crypto_unit_test.go, file_id.go, file_info.go, go.mod, go.sum, ledger_id.go, managed_network.go, network.go, network_name.go, nft_id.go, schedule_id.go, schedule_info.go, status.go, token_id.go, token_info.go, token_nft_info.go, topic_id.go, topic_info.go, transaction_record.go, transfer_transaction.go
=> Hip31 and 33

executable.go, mock_test.go, query.go, topic_message_query.go
=> fix: transaction and free query requests not cycling though nodes

transaction.go, transaction_unit_test.go
=> fix: return types changed back to struct for TransactionFromBytes()

file_append_transaction.go
=> feat: increased file append max chunk size

transaction.go
=> fix: non-exhaustive switch statement error

account_id.go, contract_function_result.go, hbar_transfer.go, internal_token_transfer.go, token_id.go, token_nft_transfer.go, token_transfer.go, transfer_transaction.go, transfer_transaction_unit_test.go
=> refactor: TransferTransaction

ecdsa_private_key.go, mock_test.go, storage_change.go
=> fix: occasional ECDSA invalid length error

account_balance_query.go, account_info_query.go, account_records_query.go, account_stakers_query.go, contract_bytecode_query.go, contract_call_query.go, contract_info_query.go, contract_info_query_unit_test.go, file_contents_query.go, file_info_query.go, live_hash_query.go, network_version_info_query.go, query.go, schedule_info_query.go, token_info_query.go, token_nft_info_query.go, topic_info_query.go, transaction_record_query.go
=> feat: added an option to get and set paymentTransactionID in queries

contract_bytecode_query_e2e_test.go, contract_call_query_e2e_test.go, contract_call_query_unit_test.go, contract_create_transaction_e2e_test.go, contract_create_transaction_unit_test.go, contract_delete_transaction_e2e_test.go, contract_execute_transaction_e2e_test.go, contract_execute_transaction_unit_test.go, contract_info_query_e2e_test.go, contract_update_transaction_e2e_test.go, examples/create_simple_contract/main.go, examples/create_stateful_contract/main.go
=> fix: e2e tests

mock_test.go, transaction.go, transaction_unit_test.go
=> feat: added transaction body validation to TransactionFromBytes

contract_function_parameters.go, contract_function_result.go, contract_function_selector.go, mock_test.go
=> feat: added support for uint24 and int24 for solidity

contract_info_query_unit_test.go, verify_signature_flow.go, verify_signature_flow_e2e_test.go
=> feat: added a flow for verifying signature

transaction_record.go
=> fix: added missing allowance fields to transaction record

transfer_transaction.go
=> feat: update TransferTransaction API for approved transfers

account_balance_query.go, account_info_query.go, account_records_query.go, account_stakers_query.go, contract_bytecode_query.go, contract_call_query.go, contract_info_query.go, examples/alias_id_example/main.go, file_contents_query.go, file_info_query.go, live_hash_query.go, network_version_info_query.go, query.go, schedule_info_query.go, token_info_query.go, token_nft_info_query.go, topic_info_query.go, transaction_receipt_query.go, transaction_record_query.go
=> fix: query payment node inconsistency

mock_test.go, topic_message_query.go, topic_message_query_e2e_test.go
=> feat: updated TopicMessageQuery to have a default start time

account_allowance_approve_transaction.go, account_info.go, examples/account_allowance/main.go, examples/schedule_transfer_example/main.go, hbar_allowance.go, schedule_create_transaction_e2e_test.go, token_allowance.go, token_nft_allowance.go
=> feat: added account allowance and schedule transfer examples

contract_function_result.go, go.mod, go.sum
=> feat: add precompile call data to ContractFunctionResults

account_allowance_delete_transaction.go, go.mod, go.sum, hbar_allowance.go, schedule_create_transaction_e2e_test.go, schedule_info.go, status.go, token_allowance.go, token_nft_allowance.go, token_nft_info.go, topic_message_query.go, transaction.go
=> feat: added AccountAllowanceDeleteTransaction

examples/account_allowance/main.go
=> feat: adding deletion to allowance example

account_id.go, account_id_unit_test.go, client_unit_test.go, id.go, transaction_id_unit_test.go, utilities_for_test.go
=> feat: added AccountID.AliasEvmAddress

CHANGELOG.md, executable.go, topic_info_query_e2e_test.go, topic_message_submit_transaction.go, transaction.go
=> fix: TopicMessageSubmitTransaction failing to send all messages

transaction_response.go
=> feat: added GetRecordQuery and GetReceiptQuery to TransactionResponse

account_create_transaction.go, account_update_transaction.go, contract_create_transaction.go, contract_delete_transaction.go, contract_update_transaction.go, schedule_create_transaction.go
=> fix: TransactionFromBytes() for certain transactions

justfile, token_mint_transaction.go, token_update_transaction.go
=> feat: adding just, a command runner

crypto.go, crypto_unit_test.go, ecdsa_public_key.go, ethereum_data_unit_test.go, ethereum_flow.go, ethereum_flow_unit_test.go, ethereum_transaction.go, ethereum_transaction_data.go, token_mint_transaction.go, token_update_transaction.go
=> feat: added EthereumFlow

account_create_transaction.go, account_info.go, account_update_transaction.go, contract_create_transaction.go, contract_info.go, contract_update_transaction.go, go.mod, go.sum, node_address.go, staking_info.go, status.go, transaction_record.go
=> feat: HIP-406 staking support

examples/staking/main.go, examples/staking_with_update/main.go
=> feat: added staking examples

executable.go
=> feat: exposed the underlying proto that was sent or received

CHANGELOG.md, account_create_transaction.go, account_info.go, account_update_transaction.go, contract_create_transaction.go, contract_info.go, contract_update_transaction.go, examples/staking/main.go, examples/staking_with_update/main.go, go.mod, go.sum, node_address.go, staking_info.go, status.go, transaction_record.go
=> Release/v2.16.0 beta.1

examples/schedule_with_expiration/main.go, schedule_info.go
=> feat: added scheduled transaction with expiration time example

token_create_transaction.go
=> fix: freezeDefault was not being set properly

CHANGELOG.md, query.go, transaction.go
Signed-off-by: Daniel Akhterov <daniel@launchbadge.com>
Fixes #533 
**Checklist**
=> fix: requests should retry on status `PLATFOR_NOT_ACTIVE`

account_create_transaction_unit_test.go, account_delete_transaction_unit_test.go, account_update_transaction_unit_test.go, contract_create_transaction_unit_test.go, contract_delete_transaction_unit_test.go, contract_execute_transaction_unit_test.go, contract_update_transaction_unit_test.go, file_create_transaction_unit_test.go, file_update_transaction_unit_test.go, token_associate_transaction_unit_test.go, token_burn_transaction_unit_test.go, token_dissociate_transaction_unit_test.go, token_fee_schedule_update_transaction_unit_test.go, token_freeze_transaction_unit_test.go, token_grant_kyc_transaction_unit_test.go, token_mint_transaction_unit_test.go, token_revoke_kys_transaction_unit_test.go, token_wipe_transaction_unit_test.go, topic_create_transaction_unit_test.go, topic_update_transaction_unit_test.go
=> feat: adding more regression unit tests

CHANGELOG.md, account_balance.go, fee_schedules.go, live_hash_delete_transaction_unit_test.go, schedule_sign_transaction_unit_test.go, token_relationship.go
=> chore: update changelog

transaction.go, transaction_unit_test.go
=> fix: Transaction.[To|From]Bytes() ignored memo

one_signature_e2e_test.go, transaction.go
=> fix: transaction hash is not singing anymore

transaction.go
=> fix: TransactionHash fails when NodeAccountIDs are not set or locked

custom_fee.go, custom_fixed_fee.go, custom_fractional_fee.go, custom_royalty_fee.go, go.mod, go.sum
=> feat: HIP-573, added CustomFee.AllCollectorsAreExempt

CHANGELOG.md
This PR modifies CHANGELOG.md in order to reflect the changes made in v2.17.6
=> chore: update v2.17.6 changelog

examples/account_create_with_hts/main.go
Description:
This PR implements the newly added features in HIP-542
Related issue(s):
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/586
Notes for reviewer:
A new example file examples/account_create_with_hts/main.go is created in order to show the mentioned in HIP-542 changes
=> Add example for HIP-542

examples/exempt_custom_fees/main.go
Description:
This PR proves that the HIP-573 is working properly.
Notes for reviewer:
A new example file examples/exempt_custom_fees/main.go is created in order to prove the functionality mentioned in HIP-573
The code basically represents initial steps to reproduce the mentioned behaviour
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/585
=> Add example for HIP-573

CHANGELOG.md, client.go, examples/account_create_with_hts/main.go, examples/exempt_custom_fees/main.go, utilities_for_test.go
Merging develop to Main for v2.17.7 Release
=> v2.17.7 Release

CHANGELOG.md, custom_fee.go, custom_fixed_fee.go, custom_fractional_fee.go, custom_royalty_fee.go, examples/exempt_custom_fees/main.go, go.mod, go.sum
This PR adds the functionality for collectors to be exempt of custom fees.
=> Add exempt custom fees

CHANGELOG.md
Update the changelog for v2.19.0
=> Update changelog for version v2.19.0

CHANGELOG.md
=> Update CHANGELOG v2.21.0

CHANGELOG.md
Updating changelog for v2.22.0
=> chore: Update changelog for v2.22.0

.github/workflows/build.yml, address_book_query_e2e_test.go, topic_message_query_e2e_test.go, utilities_for_test.go
=> Feat: Add testnet tests to PR checks

.sonarcloud.properties, sonar-project.properties
Rename config file for Sonar Cloud
Fixes #
**Checklist**
=> Rename Sonar config 

.github/workflows/build.yml
Just a workflow change to cancel previous run on a new push.
=> Fix: Cancel previous run on push

custom_fractional_fee.go, custom_fractional_fee_unit_test.go, token_create_transaction_e2e_test.go, token_nft_allowance_e2e_test.go, transaction_receipt_query_unit_test.go, transaction_record_query_unit_test.go
Just adding a setter for FeeAssessmentMethod for fractional fees and some tests.
Fixes https://github.com/hashgraph/hedera-sdk-go/issues/675
**Checklist**
- [ x ] Documented (Code comments, README, etc.)
- [ x ] Tested (unit, integration, etc.)
=> Feat: Export FeeAssessmentMethod

.github/workflows/build.yml
Just codecov fix. Seems it doesn't always work without a token.
=> Fix: Codecov CI

.sonarcloud.properties, CHANGELOG.md, account_create_transaction.go, account_create_transaction_e2e_test.go, account_create_transaction_unit_test.go, examples/create_account_with_alias/main.go, examples/create_account_with_alias_and_receiver_signature_required/main.go
Adds `SetAlias()` in `AccountCreateTransaction`
Fixes #689 
**Checklist**
=> Feat: Expand alias support

CHANGELOG.md
Just updating the changelog for v2.24.1
=> Chore: Update changelog for v2.24.1

account_allowance_adjust_transaction_unit_test.go
Just ramping up the test coverage.
=> Chore: Add AccountAllowanceAdjustTransaction Unit Tests

token_association_unit_test.go
This PR adds tests for token association functions
Fixes #
**Checklist**
=> Add tests for token_association.go

token_info.go, token_info_unit_test.go
This PR fixes a bug inside token_info.go file in `TokenInfoFromProtobuf()` function
Fixes #741
**Checklist**
=> Fix issue 741 in token_info

schedule_create_transaction_unit_test.go, token_balance_map.go, token_nft_info_query_e2e_test.go, token_pause_transaction_e2e_test.go, token_pause_transaction_unit_test.go, token_transfer_transaction_unit_test.go
This PR adds some test for some of the token transactions and info objects.
It also adds a small improvement to the token balance map.
**Checklist**
=> Added token transactions tests

token_decimal_map_unit_test.go
=> Fix: Flaky token decimal map

CHANGELOG.md, go.mod, go.sum
=> Chore: Update Changelog and dependencies for v2.25.0

CHANGELOG.md, go.mod, go.sum
Just release notes and protobuf update.
=> Chore: Update CHANGELOG and dependencies for v2.26.1

account_info_flow_e2e_test.go, contract_execute_transaction_e2e_test.go, token_nft_allowance_unit_test.go, token_nft_transfer_unit_test.go, token_pause_transaction_unit_test.go, utilities_for_test.go
This PR adds more tests to files under 65% coverage
This PR fixes some issues with integration tests
Fixes #775
**Checklist**
=> Finish up tests for at least  65% test coverage for token prefixed files

CHANGELOG.md, go.mod, go.sum
Just CHANGELOG and dependencies update.
=> Chore: Update Changelog and dependencies

managed_node.go, network_unit_test.go, node.go
This fixes some concurrency issues we had in the Node and ManagedNode structs. 
#763 
**Checklist**
- [*] Tested (unit, integration, etc.)
=> Fixed Node/ManagedNode concurrency issues

CHANGELOG.md, examples/account_allowance/main.go, go.mod, go.sum
Updated changelog for release 2.35.0
**Checklist**
=> Changelog updated for v2.35.0

CHANGELOG.md
Stable version  2.38.0
Fixes #
**Checklist**
=> release: v2.38.0

CHANGELOG.md
Release for version 2.38.1.
Fixes #
**Checklist**
=> release: v2.38.1

CHANGELOG.md
Release v2.39.0
Fixes #
**Checklist**
=> release: v2.39.0

go.mod, go.sum, status.go
Update protobufs
Fixes #979
**Checklist**
=> chore: update protobufs

CHANGELOG.md
Release v2.40.0
Fixes #
**Checklist**
=> release: v2.40.0

CHANGELOG.md
release v2.41
Fixes #
**Checklist**
=> release v2.41

crypto.go, crypto_unit_test.go, ecdsa_private_key.go, ecdsa_public_key.go, ed25519_private_key.go, ed25519_public_key.go, key_list.go, key_list_unit_test.go, transaction.go
Add missing From/To bytes functionality to Keys
Fixes #1015
**Checklist**
=> feat: Add missing Key logic

CHANGELOG.md
release v2.43
Fixes #
**Checklist**
=> release: v2.43

.golangci.yml
Exclude new linting rule G115
Fixes #
**Checklist**
=> chore: fix linting

CHANGELOG.md
Updating the change log for v2.44.0
=> release: v2.44.0

.github/workflows/build.yml, .github/workflows/main.yml, .github/workflows/previewnet.yml, .github/workflows/testnet.yml
This pull request changes the following:
- Updates the CI workflows `runs-on` labels to use the new Latitude.sh based runners.
- Closes #1043
=> ci: update workflows to use latitude.sh based runners

CHANGELOG.md
=> release: v2.45.0

executable.go, mock_test.go, query.go, transaction.go, transaction_receipt_query.go, transaction_receipt_query_unit_test.go, transaction_record_query.go, transaction_record_query_unit_test.go, utilities_for_test.go
=> chore: handle `THROTTLED_AT_CONSENSUS` and refactor retry method

CHANGELOG.md
Description:
- release: v2.46.0
=> release: v2.47.0

network_e2e_test.go, network_version_info_query_e2e_test.go, token_reject_transaction_e2e_test.go, transaction_record.go
=> chore: remove `Println` from src and test

CHANGELOG.md
=> release v2.48.0

CHANGELOG.md
=> release: v2.49.0

.github/CODEOWNERS, .github/workflows/main.yml, .github/workflows/testnet.yml
Update per Q3 audit findings
Related to #1007 
**Checklist**
=> ci: Update per Q3 audit findings

README.md, go.mod, tck/README.md, tck/go.mod, tck/go.sum
Updated the tck/README.md file to point to the right version of the sdk-tck repository
Fixes #1142
**Checklist**
=> chore: Updated tck/README.md

client.go
**Related issue(s)**: #1130
Fixes #
**Checklist**
=> chore: skip `_UpdateAddressBook` for `ClientFromConfigWithoutScheduleNetworkUpdate`

.github/workflows/build.yml, .github/workflows/main.yml, .github/workflows/previewnet.yml, .github/workflows/testnet.yml
Modifies the runner image to match the hiero runner group specification
**Related Issue(s)**:
Fixes #1146
=> chore: Updated the runners to associate with hiero-client-sdk

sdk/account_allowance_approve_transaction_unit_test.go, sdk/account_allowance_delete_transaction_unit_test.go, sdk/account_create_transaction.go, sdk/account_create_transaction_unit_test.go, sdk/account_delete_transaction_unit_test.go, sdk/account_update_transaction.go, sdk/account_update_transaction_unit_test.go, sdk/contract_create_transaction.go, sdk/contract_create_transaction_unit_test.go, sdk/contract_delete_transaction_unit_test.go, sdk/contract_execute_transaction_unit_test.go, sdk/contract_update_transaction.go, sdk/contract_update_transaction_unit_test.go
Fixes:
1. AccountCreate
2. AccountUpdate
3. ContractCreate
4. ContractUpdate
Related issue: https://github.com/hiero-ledger/hiero-sdk-go/issues/1088
=> Create additional from/to bytes tests - part 1

sdk/ethereum_transaction.go, sdk/ethereum_transaction_unit_test.go, sdk/file_append_transaction.go, sdk/file_append_transaction_unit_test.go, sdk/file_create_transaction.go, sdk/file_create_transaction_unit_test.go, sdk/file_delete_transaction_unit_test.go, sdk/file_update_transaction.go, sdk/file_update_transaction_unit_test.go, sdk/live_hash_add_transaction.go, sdk/live_hash_add_transaction_unit_test.go
Fixes:
1. EthereumTransaction
2. LiveHashTransaction
3. File transactions
Related issue: https://github.com/hiero-ledger/hiero-sdk-go/issues/1088
=> Create additional from/to bytes tests - part 2

sdk/account_allowance_approve_transaction.go, sdk/account_allowance_approve_transaction_unit_test.go, sdk/token_nft_allowance_e2e_test.go
This PR implements `DeleteTokenNftAllowanceAllSerials` method in `AccountAllowanceApproveTransaction` class.
#1225 
**Checklist**
=> chore(feat): Added `DeleteTokenNftAllowanceAllSerials` method

sdk/token_delete_transaction_unit_test.go, sdk/token_dissociate_transaction_unit_test.go, sdk/token_fee_schedule_update_transaction_unit_test.go, sdk/token_freeze_transaction_unit_test.go, sdk/token_grant_kyc_transaction_unit_test.go, sdk/token_mint_transaction_unit_test.go, sdk/token_pause_transaction_unit_test.go, sdk/token_reject_transaction_unit_test.go, sdk/token_revoke_kys_transaction_unit_test.go, sdk/token_transfer_transaction_unit_test.go, sdk/token_unfreeze_transaction_unit_test.go, sdk/token_update_nfts_transaction_unit_test.go, sdk/token_update_transaction.go, sdk/token_update_transaction_unit_test.go, sdk/token_wipe_transaction_unit_test.go, sdk/topic_create_transaction.go, sdk/topic_create_transaction_unit_test.go, sdk/topic_delete_transaction_unit_test.go, sdk/topic_message_submit_transaction.go, sdk/topic_message_submit_transaction_unit_test.go, sdk/topic_update_transaction.go, sdk/topic_update_transaction_unit_test.go
Fixes
1. sdk/topic_create_transaction.go
2. sdk/token_update_transaction.go
3. sdk/topic_update_transaction.go
Fixes: https://github.com/hiero-ledger/hiero-sdk-go/issues/1088
=> Create additional from/to bytes tests - part 4

sdk/account_allowance_approve_transaction.go, tck/cmd/server.go, tck/methods/account.go, tck/param/account.go, tck/param/allowance.go
This PR adds `AccountAllowanceApproveTransaction` endpoint listed in the following [issue](https://github.com/hiero-ledger/hiero-sdk-go/issues/1221).
Fixes: #1221
**Checklist**
=> chore(TCK): Added account allowance transaction endpoint

tck/methods/account.go, tck/methods/token.go, tck/utils/account.go, tck/utils/key.go, tck/utils/token.go
This PR removes unnecessary lint escapes and refactors repetitive logic into helper functions.
#1247 
**Checklist**
=> fix: Resolve golangci lint issues

README.md
=> chore: fix README installation command

sdk/address_book_query_e2e_test.go, sdk/token_pause_transaction.go, sdk/token_pause_transaction_e2e_test.go, sdk/token_unpause_transaction.go
This PR fixes the fromBytes -> toBytes flow for these txns.
Fixes #
**Checklist**
=> fix: token pause/unpause transactions

sdk/topic_create_transaction.go, sdk/topic_create_transaction_e2e_test.go
=> revert: automatic setting of autorenew account for topic create

examples/schedule_update_network/main.go, sdk/client.go, sdk/client_unit_test.go
=> chore: Add `ScheduledNetworkUpdate` example

sdk/mirror_node.go, sdk/node.go
=> chore: specify min TLS version

CHANGELOG.md
=> release: v2.59.0-beta.1

.github/workflows/build.yml
Adds `go mod tidy` step.
Fixes https://github.com/hiero-ledger/hiero-sdk-go/issues/1340
**Checklist**
=> ci: Add go mod tidy step

tck/Taskfile.yml, tck/docker-compose.yml
This PR is renaming TCK client image from `tck-client` to `hiero-tck-client`
**Checklist**
=> chore: Renamed TCK client image

tck/cmd/server.go, tck/methods/token.go, tck/param/token.go, tck/utils/airdrop.go
This PR adds `airdropToken` endpoint listed in the following [issue](https://github.com/hiero-ledger/hiero-sdk-go/issues/1333)
#1333
**Checklist**
=> chore(TCK): Added `airdropToken` endpoint

.github/workflows/build.yml, Taskfile.yml, examples/create_simple_contract/main.go, examples/create_stateful_contract/main.go, sdk/batch_transaction_e2e_test.go, sdk/contract_bytecode_query_e2e_test.go, sdk/contract_call_query_e2e_test.go, sdk/contract_create_flow_e2e_test.go, sdk/contract_create_transaction_e2e_test.go, sdk/contract_delete_transaction_e2e_test.go, sdk/contract_execute_transaction_e2e_test.go, sdk/contract_function_parameters_e2e_test.go, sdk/contract_id_e2e_test.go, sdk/contract_info_query_e2e_test.go, sdk/contract_update_transaction_e2e_test.go, sdk/mirror_node_contract_query_e2e_test.go, sdk/token_airdrop_transaction_e2e_test.go, sdk/token_create_transaction.go, sdk/token_create_transaction_e2e_test.go, sdk/utilities_for_test.go
Bumps services version to .62.3 and fixes regression around `TokenCreateTransaction`
Fixes #
**Checklist**
=> chore: bump services version

sdk/crypto.go, sdk/ecdsa_private_key.go, sdk/ed25519_private_key.go, sdk/token_pause_transaction.go, sdk/token_unpause_transaction.go
Various fixes and improvements
Fixes #1389
**Checklist**
=> fix: Pause/Unpause and reuse `AddSignature` in `SignTransaction `

tck/cmd/server.go, tck/methods/token.go, tck/param/token.go
This PR adds `claimToken` endpoint listed in the following [issue](https://github.com/hiero-ledger/hiero-sdk-js/issues/1386)
#1386 
**Checklist**
=> chore(TCK): Added `claimToken` endpoint

.github/workflows/build.yml
=> chore: don't require solo for unit tests

tck/cmd/server.go, tck/methods/token.go, tck/param/token.go
This PR adds `rejectToken` endpoint listed in the following [issue](https://github.com/hiero-ledger/hiero-sdk-js/issues/1406)
#1406 
**Checklist**
=> chore(TCK): Added `rejectToken` endpoint

sdk/token_create_transaction_e2e_test.go
Adds tests case where creating token with expiration time and with autorenew account
Fixes #1408
**Checklist**
=> test: TokenCreate with expiration time with autorenew account

tck/cmd/server.go, tck/methods/file.go, tck/param/file.go
=> feat(TCK): File methods

.github/workflows/build.yml
=> chore: bump solo action

sdk/abi_decode.go
Go 1.21 adds built-in functions min and max.   https://tip.golang.org/doc/go1.21
Therefore, we can directly remove our own implementations and use the built-in function with the same names. 
Fixes #
**Checklist**
=> chore: remove unused min func

sdk/token_balance_map.go, sdk/token_decimal_map.go, tck/cmd/server.go, tck/go.mod, tck/go.sum, tck/methods/account.go, tck/param/account.go, tck/response/account.go
Add TCK method for account balance query
Fixes #1513
**Checklist**
=> feat: add TCK method for account balance query

sdk/transfer_transaction.go
fix some inconsistent function name in comment
Fixes #
**Checklist**
=> chore: fix some inconsistent function name in comment
